name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          'Hello @{}! Thank you for your interest in this project. 
          Your issue will be reviewed as fast as possible and contacted if any answers or clarifications are needed.'
        pr-message: |
          'Hello @{}! Thank you for your contribution 💪
          As it's your first contribution be sure to check out the CONTRIBUTING.md.
          If you have any queries or issue, feel free to ask in Discussions or Issues.
          Welcome aboard ⛵️!'
