name: Release

on:
  push:
    branches:
    - "!*"
    tags:
    - "v*.*.*"

jobs:
  Release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install Poetry
        run: pip install poetry

      - name: Initializing Project
        run: poetry install 

      - name: Running Test Cases
        run: poetry run pytest

      - name: Build project for distribution
        run: poetry build

      - name: Check Version
        run: |
          if [[ "$(poetry version -s)" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]
          then
            echo "::set-output name=prerelease::false"
          else
            echo "::set-output name=prerelease::true"
          fi
        id: check-version

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "dist/*"
          draft: false
          prerelease: steps.check-version.outputs.prerelease == 'true'

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish
